let myDishes = [
    {
        name: "Classic Cheeseburger",
        category: "main",
        price: 9.90,
        description: "Rindfleisch-Patty mit Cheddar, Salat, Tomate, Zwiebeln und Burger-Sauce.",
        rating: 3,
        amount: 1,
    },
    {
        name: "Bacon BBQ Burger",
        category: "main",
        price: 11.50,
        description: "Rindfleisch mit knusprigem Bacon, BBQ-Sauce, Cheddar und Röstzwiebeln.",
        rating: 4,
        amount: 1,
    },
    {
        name: "Veggie Delight Burger",
        category: "main",
        price: 8.90,
        description: "Hausgemachter Gemüse-Patty mit Avocado, Tomate, Salat und Joghurtsauce.",
        rating: 2,
        amount: 1,
    },
    {
        name: "Double Trouble Burger",
        category: "main",
        price: 13.80,
        description: "Doppelte Rindfleisch-Pattys, doppelt Käse, Bacon und Extra-Sauce.",
        rating: 3,
        amount: 1,
    },
    {
        name: "Hot Chili Burger",
        category: "main",
        price: 10.90,
        description: "Feuriger Burger mit Jalapeños, scharfer Sauce und Pepper Jack Cheese.",
        rating: 4,
        amount: 1,
    },
    {
        name: "Chicken Crunch Burger",
        category: "main",
        price: 9.50,
        description: "Knusprig paniertes Hähnchenfilet mit Honig-Senf-Sauce und Cole Slaw.",
        rating: 5,
        amount: 1,
    },
    {
        name: "Pulled Pork Burger",
        category: "main",
        price: 11.20,
        description: "Zartes Pulled Pork in BBQ-Sauce mit Krautsalat auf Brioche-Bun.",
        rating: 4,
        amount: 1,
    },
    {
        name: "Falafel Burger",
        category: "main",
        price: 8.70,
        description: "Falafel-Patty mit Hummus, Gurke, Tomate und Tahini-Dressing – vegan!",
        rating: 3,
        amount: 1,
    },
    {
        name: "Truffle Burger",
        category: "main",
        price: 12.90,
        description: "Rindfleisch-Burger mit Trüffel-Mayo, Rucola und Parmesan.",
        rating: 5,
        amount: 1,
    },
    {
        name: "Kids Burger",
        category: "main",
        price: 6.50,
        description: "Kleiner Burger mit Patty, Käse und Ketchup – für die Kleinen.",
        rating: 4,
        amount: 1,
    },
    {
      name: "Pommes frites",
      category: "side",
      price: 3.50,
      description: "Knusprig frittierte Kartoffelstäbchen mit Salz",
      rating: 4,
      amount: 1,
    },
    {
      name: "Süßkartoffel-Pommes",
      category: "side",
      price: 4.00,
      description: "Süßlich-knusprige Pommes aus Süßkartoffeln",
      rating: 5,
      amount: 1,
    },
    {
      name: "Onion Rings",
      category: "side",
      price: 3.80,
      description: "Frittierte Zwiebelringe mit knuspriger Panade",
      rating: 4,
      amount: 1,
    },
    {
      name: "Cole Slaw",
      category: "side",
      price: 2.90,
      description: "Frischer amerikanischer Krautsalat mit cremigem Dressing",
      rating: 2,
      amount: 1,
    },
    {
      name: "Mozzarella-Sticks",
      category: "side",
      price: 4.20,
      description: "Frittierte Käse-Sticks mit würziger Panade",
      rating: 3,
      amount: 1,
    },
    {
      name: "Mac and Cheese",
      category: "side",
      price: 4.50,
      description: "Käsenudeln nach amerikanischer Art – cremig und herzhaft",
      rating: 2,
      amount: 1,
    }
  ];

  //*category, main dish - side dish, zum filtern